### ISSUE TITLE
energy savings

### ISSUE THREAD

**Issue by jellevervloessem** [nakulbende/Make-Eufy-Smart-Again#1]
Hi @nakulbende, 

Do you have any update on exploring to putting ESP in sleep/ switch off telemetry at night?

**Comment by nakulbende** [comment]
I do, lemme write this up.

------------Sent from phone----------

Nakul Bende,

Materials Scientist, Formlabs Inc.

http://nakulbende.com

**Comment by nakulbende** [comment]
Heyo, I updated my github repo
https://github.com/nakulbende/Make-Eufy-Smart-Again

I dropped wake/ skeep plan as it is quite unreliable. Alternatively, I just
powered it directly from Eufy's battery, which works like a charm. > 6
months without an issue.



Nakul Bende,

Materials Scientist, Formlabs Inc.

http://nakulbende.com


- Ever tried. Ever failed. Try Again. Fail again. Fail better.

--Samuel Beckett
