### ISSUE TITLE
Question...unmounted?

### ISSUE THREAD

**Issue by vulcanjedi** [nakulbende/Make-Eufy-Smart-Again#2]
But curious why this has to be mounted at all?
is it because the IR signal not strong enough?
I was hoping to find a project such as this where small esp8266 close enough to the base to just start adhoc cleaning when I wanted?
Currently we have the robovac in the basement and we have a ledge across the room I was hoping to just aim the esp from?
Would this use case work?
Sorry this would be my first esp8266 project

**Comment by nakulbende** [comment]
Hey,

Thanks for searchng through my repo - yes youc an have the esp8266
anywhere. Honestly, if you Eufy/ cleaner is constrained to one room, it
might be a lot easier to do that, and just power through a USB outlet. I
mounted it for having all-time control even when it is going to other rooms
that the one my base is in.

I think IR signals are pretty good, not omnipresent, but good enough for a
single room. Good idea!



Nakul Bende,

Materials Scientist, Formlabs Inc.

http://nakulbende.com


- Ever tried. Ever failed. Try Again. Fail again. Fail better.

--Samuel Beckett

**Comment by vulcanjedi** [comment]
Thanks for reply, super excited to try to take this on.  Maybe relocate the base to be more centrally located so it can return to the base. Currently shutting the doors to other rooms since we dont frequent the basement all that much yet. But yeah I think the mount is too much for me, but was still hoping to try the project as  good learning opportunity. Thanks for sharing.

**Comment by nakulbende** [comment]
ESp8266 is awesome - choose your module well if you havent bought. I would
go for one of the nodemcu dev board - no need to make a flashing circuits
and all - and it already has a usb port which you can use to charge. Good
luck! Happy to help, and do share photos!



Nakul Bende,

Materials Scientist, Formlabs Inc.

http://nakulbende.com


- Ever tried. Ever failed. Try Again. Fail again. Fail better.

--Samuel Beckett
